{
 "title": "BFTList",
 "description": "Dashboard for BFTList.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System setting",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Average latency",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(host_latency)" }
   ]
  },
  {
   "title": "Average message rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(irate(msg_sent_total[1m]))" }
   ]
  },
  {
   "title": "Average request execution time",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg(client_req_exec_time) by (client_id,timestamp))"
    }
   ]
  },
  {
   "title": "State length",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max(state_length_total)" }
   ]
  },
  { "title": "Algorithm stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average client request execution time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(avg(client_req_exec_time) by (client_id,timestamp))",
     "legendFormat": "Average request execution time"
    },
    { "expr": "max(state_length_total)", "legendFormat": "State length" }
   ]
  },
  {
   "title": "Message rate per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(msg_sent_total[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Average bytes per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(bytes_sent_total[5m])) by (com_mod)",
     "legendFormat": "{{com_mod}}"
    }
   ]
  },
  {
   "title": "Average latency per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(host_latency) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "View change latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(allow_service_rtt) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average size of message",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(msg_sent_size{com_mod=\"ZERO_MQ\"}) by (msg_type)",
     "legendFormat": "{{msg_type}}"
    }
   ]
  },
  { "title": "System health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average number of messages in queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(msgs_in_queue > 0) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Messages sent per node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "msg_sent_total", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  }
 ]
}